"""Add referrer_id to User

Revision ID: aa8c55163086
Revises: d05130208e97
Create Date: 2024-11-17 09:12:47.437146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8c55163086'
down_revision: Union[str, None] = 'd05130208e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
